kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-pipelines-scc-privileged
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
