kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-privileged-scc
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: demo-pipelines
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: demo-pipelines-scc-privileged
