apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: rebuild
spec:
  params:
  - name: deployment-name
    description: name of the deployment to be patched
  - name: git-url
    description: url of the git repo for the code of deployment
  - name: git-revision
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    description: image to be build from the code
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: my-event-pipeline-
    spec:
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/demo-pipelines/vote-ui
      - name: deployment-name
        value: vote-ui
      - name: git-url
        value: https://github.com/apoczekalewicz/pipelines-vote-ui/
      pipelineRef:
        name: build-and-deploy
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: source-pvc

